version: '3.8'

services:
  # --- SERVER ĐIỀU PHỐI (NGINX) ---
  nginx-lb:
    image: nginx:latest
    container_name: netsuggest-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro  # Đọc trực tiếp thư mục dist bạn vừa build bằng tay
    depends_on:
      - backend-1
      - backend-2
    networks:
      - netsuggest-net

  # --- SERVER CHÍNH (BACKEND 1) ---
  backend-1:
    build: ./backend
    container_name: netsuggest-backend-1
    environment:
      - SERVER_ID=backend-1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.xomvatjznjjqplifhkej
      - SPRING_DATASOURCE_PASSWORD=Tg9ABbc1yP8nh5DT
      - SUPABASE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbXZhdGp6bmpqcXBsaWZoa2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzg3MjAsImV4cCI6MjA5MTc1NDcyMH0.gNiIeYjipqcQJvJNwa2l6YmaMpv8dMxoc0SiYbZos3g
    networks:
      - netsuggest-net

  # --- SERVER DỰ PHÒNG (BACKEND 2) ---
  backend-2:
    build: ./backend
    container_name: netsuggest-backend-2
    environment:
      - SERVER_ID=backend-2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.xomvatjznjjqplifhkej
      - SPRING_DATASOURCE_PASSWORD=Tg9ABbc1yP8nh5DT
      - SUPABASE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbXZhdGp6bmpqcXBsaWZoa2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzg3MjAsImV4cCI6MjA5MTc1NDcyMH0.gNiIeYjipqcQJvJNwa2l6YmaMpv8dMxoc0SiYbZos3g
    networks:
      - netsuggest-net

networks:
  netsuggest-net:
    driver: bridge