# Cấu hình server
server.port=8080
server.servlet.context-path=/api

# Spring Security OAuth2 Client
spring.security.oauth2.client.registration.microsoft.client-id=e1fe9d19-3d50-458a-908a-a6a5d92ba91b
spring.security.oauth2.client.registration.microsoft.client-secret=kBU8Q~Tw-YCkJGTaeP1FpTZ_1M6~bjXr6jMa7cCY
spring.security.oauth2.client.registration.microsoft.scope=openid, profile, email, offline_access
# QUAN TRỌNG: Phải có dòng này
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
# Redirect URI: Để Spring xử lý, hãy dùng đúng format của Spring Security
spring.security.oauth2.client.registration.microsoft.redirect-uri={baseUrl}/login/oauth2/code/microsoft

# Thay {tenant-id} bằng ID thực tế của bạn hoặc 'common' cho multi-tenant
spring.security.oauth2.client.provider.microsoft.issuer-uri=https://login.microsoftonline.com/e1fe9d19-3d50-458a-908a-a6a5d92ba91b/v2.0