events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream backend_cluster {
        # Cơ chế ip_hash giúp user không bị logout khi nhảy giữa 2 server
        ip_hash; 
        server backend-1:8080;
        server backend-2:8080;
    }

    server {
        listen 80;

        # 1. Phục vụ Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # 2. Điều hướng API tới Cluster Backend (Load Balancing)
        location /api/ {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}