# ==========================================
# DATABASE: POSTGRESQL (SUPABASE)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.xomvatjznjjqplifhkej
spring.datasource.password=Tg9ABbc1yP8nh5DT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# ==========================================
# SUPABASE JWT CONFIGURATION
# ==========================================
supabase.jwt.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbXZhdGp6bmpqcXBsaWZoa2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzg3MjAsImV4cCI6MjA5MTc1NDcyMH0.gNiIeYjipqcQJvJNwa2l6YmaMpv8dMxoc0SiYbZos3g

# ==========================================
# SERVER & SESSION CONFIGURATION
# ==========================================
server.servlet.session.timeout=6h
server.servlet.session.cookie.path=/

# ==========================================
# THIRD-PARTY API CONFIGURATION
# ==========================================
trackasia.api.url=https://maps.track-asia.com
trackasia.api.key=fbe052e2f17788443245e0c54f3084b0a2